<?xml version="1.0" encoding="UTF-8"?>
<CST:Node xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:CST="http://gts.inf.um.es/modernization/cst" kind="CST">
  <children xsi:type="CST:Node" kind="file">
    <children xsi:type="CST:Leaf" kind="path" value="C:\Users\martyn.ellison\git\gra2mol\examples\Grammar2Model.examples.PLSQL2ASTMModel\plsql-files\sharepoint_AdminContent.sql"/>
    <children xsi:type="CST:Leaf" kind="filename" value="sharepoint_AdminContent.sql"/>
    <children xsi:type="CST:Node" kind="sql_dump">
      <children xsi:type="CST:Node" kind="create_table">
        <children xsi:type="CST:Leaf" kind="CREATE" value="CREATE" line="1"/>
        <children xsi:type="CST:Leaf" kind="TABLE" value="TABLE" pos="7" line="1"/>
        <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="13" line="1"/>
        <children xsi:type="CST:Leaf" kind="IDENTIFER" value="SiteQuota" pos="14"
            line="1"/>
        <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="23"
            line="1"/>
        <children xsi:type="CST:Leaf" kind="OPEN_BRKT" value="(" pos="24" line="1"/>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="2"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="SiteId" pos="2" line="2"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="8"
              line="2"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="10"
                line="2"/>
            <children xsi:type="CST:Leaf" kind="UNIQUEIDENTIFIER" value="uniqueidentifier"
                pos="11" line="2"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="27"
                line="2"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="29" line="2"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="33" line="2"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="37" line="2"/>
        </children>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="3"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="SessionId" pos="2"
              line="3"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="11"
              line="3"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="13"
                line="3"/>
            <children xsi:type="CST:Leaf" kind="INT" value="smallint" pos="14" line="3"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="22"
                line="3"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="24" line="3"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="28" line="3"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="32" line="3"/>
        </children>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="4"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="SMOpCode" pos="2"
              line="4"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="10"
              line="4"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="12"
                line="4"/>
            <children xsi:type="CST:Leaf" kind="INT" value="tinyint" pos="13" line="4"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="20"
                line="4"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="22" line="4"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="26" line="4"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="30" line="4"/>
        </children>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="5"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="DocId" pos="2" line="5"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="7"
              line="5"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="9"
                line="5"/>
            <children xsi:type="CST:Leaf" kind="UNIQUEIDENTIFIER" value="uniqueidentifier"
                pos="10" line="5"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="26"
                line="5"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="28" line="5"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="32" line="5"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="36" line="5"/>
        </children>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="6"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="DiskUsed" pos="2"
              line="6"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="10"
              line="6"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="12"
                line="6"/>
            <children xsi:type="CST:Leaf" kind="INT" value="bigint" pos="13" line="6"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="19"
                line="6"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="21" line="6"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="25" line="6"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="29" line="6"/>
        </children>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="7"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="UpdateTimeStamp" pos="2"
              line="7"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="17"
              line="7"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="19"
                line="7"/>
            <children xsi:type="CST:Leaf" kind="BIT" value="bit" pos="20" line="7"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="23"
                line="7"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="25" line="7"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="29" line="7"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="33" line="7"/>
        </children>
        <children xsi:type="CST:Node" kind="column">
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="1"
              line="8"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="SQId" pos="2" line="8"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="6"
              line="8"/>
          <children xsi:type="CST:Node" kind="data_type">
            <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="8"
                line="8"/>
            <children xsi:type="CST:Leaf" kind="INT" value="int" pos="9" line="8"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="12"
                line="8"/>
            <children xsi:type="CST:Leaf" kind="IDENTITY" value="IDENTITY" pos="14"
                line="8"/>
            <children xsi:type="CST:Leaf" kind="OPEN_BRKT" value="(" pos="22" line="8"/>
            <children xsi:type="CST:Leaf" kind="NUMBER" value="1" pos="23" line="8"/>
            <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="24" line="8"/>
            <children xsi:type="CST:Leaf" kind="NUMBER" value="1" pos="25" line="8"/>
            <children xsi:type="CST:Leaf" kind="CLOSE_BRKT" value=")" pos="26" line="8"/>
          </children>
          <children xsi:type="CST:Node" kind="column_optitions">
            <children xsi:type="CST:Leaf" kind="NOT" value="NOT" pos="28" line="8"/>
            <children xsi:type="CST:Leaf" kind="NULL" value="NULL" pos="32" line="8"/>
          </children>
          <children xsi:type="CST:Leaf" kind="COMMA" value="," pos="36" line="8"/>
        </children>
        <children xsi:type="CST:Node" kind="constraint">
          <children xsi:type="CST:Leaf" kind="CONSTRAINT" value="CONSTRAINT" pos="1"
              line="9"/>
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="12"
              line="9"/>
          <children xsi:type="CST:Leaf" kind="IDENTIFER" value="SiteQuota_SiteId"
              pos="13" line="9"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="29"
              line="9"/>
          <children xsi:type="CST:Leaf" kind="PRIMARY" value="PRIMARY" pos="31" line="9"/>
          <children xsi:type="CST:Leaf" kind="KEY" value="KEY" pos="39" line="9"/>
          <children xsi:type="CST:Leaf" kind="CLUSTERED" value="CLUSTERED" pos="43"
              line="9"/>
          <children xsi:type="CST:Leaf" kind="OPEN_BRKT" value="(" line="10"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_BRKT" value=")" line="16"/>
        </children>
        <children xsi:type="CST:Node" kind="table_opitions">
          <children xsi:type="CST:Leaf" kind="WITH" value="WITH" pos="1" line="16"/>
          <children xsi:type="CST:Leaf" kind="OPEN_BRKT" value="(" pos="6" line="16"/>
          <children xsi:type="CST:Leaf" kind="FILLFACTOR" value="FILLFACTOR" pos="124"
              line="16"/>
          <children xsi:type="CST:Leaf" kind="EQUALS" value="=" pos="135" line="16"/>
          <children xsi:type="CST:Leaf" kind="NUMBER" value="95" pos="137" line="16"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_BRKT" value=")" pos="139" line="16"/>
          <children xsi:type="CST:Leaf" kind="ON" value="ON" pos="141" line="16"/>
          <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="144"
              line="16"/>
          <children xsi:type="CST:Leaf" kind="PRIMARY" value="PRIMARY" pos="145" line="16"/>
          <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="152"
              line="16"/>
        </children>
        <children xsi:type="CST:Leaf" kind="CLOSE_BRKT" value=")" line="17"/>
        <children xsi:type="CST:Leaf" kind="ON" value="ON" pos="2" line="17"/>
        <children xsi:type="CST:Leaf" kind="OPEN_SQUARE_BRKT" value="[" pos="5" line="17"/>
        <children xsi:type="CST:Leaf" kind="PRIMARY" value="PRIMARY" pos="6" line="17"/>
        <children xsi:type="CST:Leaf" kind="CLOSE_SQUARE_BRKT" value="]" pos="13"
            line="17"/>
        <children xsi:type="CST:Leaf" kind="GO" value="GO" line="18"/>
      </children>
    </children>
  </children>
</CST:Node>
